on:
  pull_request:
    branches:
      - master

name: flexdash

jobs:
  flexdash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("readr", "knitr", "leaflet", "flexdashboard", "rmarkdown"), dependencies = TRUE)'
      - name: Run R script
        run: |
          Rscript -e "render("./index.Rmd", "flex_dashboard")"
