on:
  pull_request:
    branches:
      - master

name: flexdash

jobs:
  flexdash:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master

      - uses: r-lib/actions/setup-pandoc@v1
      - name: Cache R packages
        uses: actions/cache@v1
        with:
          path: /home/runner/work/_temp/Library
          key: ${{ runner.os }}-r-3.6-${{ hashFiles('DESCRIPTION') }} 

      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("readr", "leaflet", "flexdashboard", "rmarkdown"))'
      - name: Run R script
        run: |
          Rscript -e "rmarkdown::render('index.Rmd')"
      - name: commit
        run: |
          git config user.email "m1s1ng@outlook.com"
          git config user.name "bjungbogati"
          git add .
          git commit -m 'Re-build index.Rmd' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
