on:
  pull_request:
    branches:
      - master

name: flexdash

jobs:
  flexdash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: |
          Rscript -e 'install.packages(c("readr", "leaflet", "flexdashboard", "rmarkdown"))'
      - name: Run R script
        run: |
          Rscript -e "rmarkdown::render('index.Rmd')"
      - name: commit
        run: |
          git add .
          git commit -m 'update index file'
      - uses: r-lib/actions/pr-push@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}




